language: node_js
node_js:
- 8.12.0
after_success:
- npm run coveralls
env:
  global:
    secure: eHuxX5uxoCk2IQItQWHx6NVsagWF+ZBPfntd02i8Amtk7I64nqO3MKyW5ObLirvrkwxXMixBeh2VAOHtdOsE/tnSlnLV+lwNzX4lQL5p0UT3KtNmRL0FCe51IQ0JESjDrh0BcoqnVnQM3CswnC1Dzay9rNKczuHI3DhQO3YchErQ+bU0EYDTuxJB4KaXYBm942nVIDTMfIvBhan6omAKI2tTe03WHg02TydhTvGCLP3/Xlej0wLHpcMEnxk8bTWGbvLLR1qQWqPwSJFmU+xMxyMXhH4OlHD9jFqwuDlwlAVG13yUN97/rBi58hWI+xiReYAzCkVugoEnb67CjQfMBoR9dOlTonVaAApwYvFb8pR1jCrWMI8dlskNyAz5dq4XjTX9cTxvLBTpso40YN+x3CCSNGpZ3IcbD35uIZ0AkDcmtyzo35GuSepkCvAyS82y3mBSJKM/53y1MDhA33+RgIfcjQbndcjlpzJWa3Uk521AeFVHApqTqT46shEARR0cNvIhut/LSt+n2A8q37z0JDEZp7dcE0Ww6sR3hA5Ybr4cUhVu14PT+I+YjZMovuEwaN1Lu+kGn3elj96IVFVQAGOllU2KHGxkut1B829bREZoHNrBXU95Iy9VFToRdK1ggRXfwlhO2oIzCDDEIv98LpnjBB6VRhY4v3HtwgbRcOA=
